name: Example Custom Configuration
description: 'This will provide you a way to access/update configuration.'
type: module

package: custom
# core: '8.x'
configure: example.configuration

version: '8.x-1.2'
core: '8.x'
project: 'example'

