global-style: # Libraries needed in all pages.
  css:
    theme:
      'https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700': { type: external }
      css/animate.css: {}
      css/magnific-popup.css: {}
      css/bootstrap.css: {}
      css/icomoon.css: {}
      css/style.css: {}
      css/custom.css: {}  

  js:
    'http://code.jquery.com/jquery-migrate-3.0.0.js': { type: external, minified: true }
    js/jquery.easing.1.3.js: {}
    js/bootstrap.min.js: {}
    js/jquery.waypoints.min.js: {}
    js/jquery.stellar.min.js: {}
    js/main.js: {} 
  
  dependencies:
    - core/drupalSettings
    - core/drupal
    - core/jquery

fontawesome:
  version: 1.x
  css:
    theme:
      lib/fonts/css/font-awesome.css: {}
